### ISSUE TITLE
Unable to handle: undefined local variable or method `host' for #<ApnMachine::Server::Client:0x007fbe720a21d8>

### ISSUE THREAD

**Issue by ghost** [jnak/apnmachine#7]
I think I'm doing this right, but I keep getting this error in the log:
   "Unable to handle: undefined local variable or method `host' for #ApnMachine::Server::Client:0x007fbe720a21d8"

Here is my code:

``` ruby
ApnMachine::Config.redis = Redis.new
notification = ApnMachine::Notification.new
notification.device_token = my_device_token
notification.alert = 'hello'
notification.push
```

Rails 3.2.6 - everything running localhost.

**Comment by jnak** [comment]
what redis client do you use ?

**Comment by ghost** [comment]
bundle list shows "redis (2.2.2)".

**Comment by jnak** [comment]
where do you get the error ? in rails or the server process ?

**Comment by ghost** [comment]
On the apnmachined log. I'm not running as a daemon.

I'm trying to send the notification from the Rails console.

**Comment by jnak** [comment]
Ok, then. How do you start the server?

On 11 juil. 2012, at 17:37, Phill Kenoyer
reply@reply.github.com
wrote:

**Comment by ghost** [comment]
I have tried with and without bundle exec

```
bundle exec apnmachined --pem config/certs/apn_production.pem
```

Here is the full console output:

<pre>
deploy@staging$ bundle exec apnmachined --pem config/certs/apn_production.pem
I, [2012-07-12T17:00:00.035131 #20145]  INFO -- : Connecting to Apple Servers
I, [2012-07-12T17:00:00.076611 #20145]  INFO -- : Starting APN Server on Redis
I, [2012-07-12T17:00:00.105656 #20145]  INFO -- : Connection to Apple Servers completed
&lt;SSL_incomp&gt;I, [2012-07-12T17:00:00.311641 #20145]  INFO -- : Connection closed
D, [2012-07-12T17:00:25.926670 #20145] DEBUG -- : TOKEN:[removed for privacy] | ALERT:{"aps"=>{"alert"=>"hello"}}
E, [2012-07-12T17:00:25.926873 #20145] ERROR -- : Reconnecting connection to APN
D, [2012-07-12T17:00:25.928521 #20145] DEBUG -- : Sending notification to APN
E, [2012-07-12T17:00:25.928826 #20145] ERROR -- : Unable to handle: undefined local variable or method `host' for #&lt;ApnMachine::Server::Client:0x00000001d76da0&gt;
I, [2012-07-12T17:00:25.968099 #20145]  INFO -- : Connection to Apple Servers completed
&lt;SSL_incomp&gt;I, [2012-07-12T17:00:26.131432 #20145]  INFO -- : Connection closed
</pre>


I was using APN Sender and it was nice except they were monkey patching rails and breaking things. It uses Resque.
I switched to Rapns and it runs fine but I don't like it polling the DB.

So I know that sending notifications works fine. I just don't know if I'm doing something wrong or if there is a bug in apnmachine. I have tried on my Mac and also my Debian staging server on Linode.

PS, I just now noticed the SSL_incomp in the log output. Same on my server.

**Comment by ghost** [comment]
Found the error.

In client.rb line 22
Config.logger.debug "#{Time.now} [#{host}:#{port}] New notif"

host and port do not exist. I think they should be apn_host and apn_port. I changed it to that and my notifications work now.

**Comment by ghost** [comment]
Strange, it's already fixed in master.

Changed my Gemfile to read:

```
gem 'apnmachine', git: 'https://github.com/jnak/apnmachine.git', branch: 'master'
```

Now I'm all set.
